apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Secret
metadata:
  name: qubehub-env
  namespace: apps
type: Opaque
stringData:
  ADDR: ":32003"
  SCYLLA_HOSTS: "192.168.1.87"
  SCYLLA_KEYSPACE: "qube_hub"
  SCYLLA_USERNAME: ""
  SCYLLA_PASSWORD: ""
  JWT_SECRET: "cd609f60f2fd459cc82ca31f789da20a1a2fafa6807896b83f625a6279fc3102e2e0fcde"
  STORAGE_PATH: "/app/storage/images"
  MAX_UPLOAD_SIZE: "5368709120"
  DISABLE_AT_MIN_REPORTS: "5"
  ADMIN_EMAIL: "ewen@macculloch.net"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qubehub-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qubehub
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: qubehub
  template:
    metadata:
      labels:
        app: qubehub
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsNonRoot: true
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: qubehub
          image: registry.ewenmacculloch.com/qubehub:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: qubehub-env
          ports:
            - name: http
              containerPort: 32003
          volumeMounts:
            - name: qubehub-data
              mountPath: /app/storage
            - name: qubehub-data
              mountPath: /app/static/avatars
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: qubehub-data
          persistentVolumeClaim:
            claimName: qubehub-data
---
apiVersion: v1
kind: Service
metadata:
  name: qubehub
  namespace: apps
spec:
  type: NodePort
  selector:
    app: qubehub
  ports:
    - name: http
      port: 32003
      targetPort: http
      nodePort: 32003
