[package]
name = "Qube"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26"
libc = "0.2"
colored = "3.0.0"
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking"] }
indicatif = "0.17"