apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qube-rootpage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Voyrox/Qube.git
    targetRevision: main
    path: qube-apps/rootPage
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
