apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qube
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: qube
  template:
    metadata:
      labels:
        app: qube
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-syd-worker-01
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: qube
          image: registry.ewenmacculloch.com/qube:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 32002
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: qube
  namespace: apps
spec:
  type: NodePort
  selector:
    app: qube
  ports:
    - name: http
      port: 32002
      targetPort: http
      nodePort: 32002
