title: Qube User and Developer Documentation
description: Qube: A container runtime written in Rust.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-include-cache

just_the_docs:
  custom_styles: "docs/assets/css/custom.css"