title: Qube User & Dev Documentation
description: A container runtime written in Rust.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/Voyrox/Qube

plugins:
  - jekyll-include-cache

just_the_docs:
  custom_styles: "assets/css/custom.css"