source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"  # Ensure compatibility with GitHub Pages
gem "just-the-docs", "0.10.1"  # Use the exact version you're using
gem "webrick" # Uncomment if you have Ruby >= 3 and Jekyll <= 4.2.2
